<?php
/**
 * Interface for URL filter
 * 
 * @package CPF
 * @subpackage Core
 */
interface Cpf_Core_Url_IFilter
{
	/**
	 * Method executes before routing is performed
	 * 
	 * @param Cpf_Core_Request $request
	 * @return void
	 */
	public function filter_pre(Cpf_Core_Request $request);

	/**
	 * Method executes after routing is performed
	 * 
	 * @param Cpf_Core_Request $request
	 * @return void
	 */
	public function filter_post(Cpf_Core_Request $request);
	
	/**
	 * Method executes before generating outgoing link using particular URL route  
	 * 
	 * @param array &$params Params passed to generate the link
	 * @return void
	 */
	public function filter_reverse_pre(array &$params);
	
	/**
	 * Method executes after generating outgoing link using particular URL route  
	 * 
	 * @param string &$url URL that was generated by URL route 
	 * @param array &$params Params passed to generate the link
	 * @return void
	 */
	public function filter_reverse_post(&$url, array &$params);
}
?>