<div class="b-terms b-privacy-wrapper l-center">
	<h1 class="baltica-plain">Terms of Use</h1>
	<div class="b-privacy-l">
		<p class="b-terms-subtitle no-margin">ATTENTION: PLEASE READ THESE TERMS CAREFULLY BEFORE USING THIS WEBSITE. USING THIS WEBSITE INDICATES THAT YOU ACCEPT THESE TERMS. IF YOU DO NOT ACCEPT THESE TERMS (”TERMS”), DO NOT USE THIS WEBSITE.</p>
		<p class="definition">Use of site</p>
		<p class="no-margin">Talon Lodge authorizes you to view and download the materials at this website (”Site”) only for your personal, non-commercial use, provided that you retain all copyright and other proprietary notices contained in the original materials or any copies of the materials. You may not modify the materials at this Site in any way or reproduce or publicly display, perform, or distribute or otherwise use them for any public or commercial purpose. Any use of these materials on any other website or networked computer environment for any purpose is prohibited. The materials at this Site are copyrighted and any unauthorized use of any materials at this Site may violate copyright, trademark, and other laws. If you breach any of these Terms, your authorization to use this Site automatically terminates and you must immediately destroy any downloaded or printed materials.</p>
		<p class="definition">Disclaimers</p>
		<p class="no-margin">THE MATERIALS (INCLUDING ALL SOFTWARE) AND SERVICES AT THIS SITE ARE PROVIDED “AS IS” WITHOUT WARRANTIES OF ANY KIND INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF INTELLECTUAL PROPERTY. Talon Lodge’s obligations with respect to its products and services are governed solely by the agreements under which they are provided and nothing on this Site should be construed to alter such agreements. Talon Lodge further does not warrant the accuracy and completeness of the materials, software or services at this Site. Talon Lodge may make changes to the materials and services at this Site, or to the products and prices described in them, at any time without notice. The materials and services at this Site may be out of date, and Talon Lodge makes no commitment to update the materials and services at this Site. Information published at this Site may refer to products, programs or services that are not available in your country. Consult your local Talon Lodge business contact for information regarding the products, programs and services that may be available to you. Applicable law may not allow the exclusion of implied warranties, so this exclusion may not apply to you.</p>
		<p class="definition">Limitation of liability</p>
		<p class="no-margin">IN NO EVENT WILL TALON LODGE, ITS SUPPLIERS, OR OTHER THIRD PARTIES MENTIONED AT THIS SITE BE LIABLE FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM LOST PROFITS, LOST DATA OR BUSINESS INTERRUPTION) ARISING OUT OF THE USE, INABILITY TO USE, OR THE RESULTS OF USE OF THIS SITE, ANY WEBSITES LINKED TO THIS SITE, OR THE MATERIALS OR INFORMATION OR SERVICES CONTAINED AT ANY OR ALL SUCH SITES, WHETHER BASED ON WARRANTY, CONTRACT, TORT OR ANY OTHER LEGAL THEORY AND WHETHER OR NOT Talon Lodge HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IF YOUR USE OF THE MATERIALS, INFORMATION OR SERVICES FROM THIS SITE RESULTS IN THE NEED FOR SERVICING, REPAIR OR CORRECTION OF EQUIPMENT OR DATA, YOU ASSUME ALL COSTS THEREOF. APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THESE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU.</p>
		<p class="definition">Use of software</p>
		<p class="no-margin">Any software that is made available to download from this Site is the copyrighted work of Talon Lodge and/or its suppliers. Use of the software is governed by the terms of the end user license agreement, if any, which accompanies or is included with the software (”License Agreement”). You may not download or install any Software that is accompanied by or includes a License Agreement unless you have read and accepted the terms of the License Agreement. REPRODUCTION OR REDISTRIBUTION OF THE SOFTWARE IS PROHIBITED EXCEPT AS PROVIDED FOR IN THE APPLICABLE LICENSE AGREEMENT.</p>
		<p class="definition">User submissions</p>
		<p class="no-margin">Talon Lodge does not want to receive confidential or proprietary information from you through this Site. Any material, information or other communication (”Communications”) you transmit or post to this Site will be considered non-confidential and non-proprietary. Talon Lodge will have no obligations with respect to the Communications. Talon Lodge and its designees will be free to copy, disclose, distribute, incorporate and otherwise use the Communications and all data, images, sounds, text, and other things embodied therein for any and all commercial or non-commercial purposes. Personally identifiable information that you submit to Talon Lodge for the purpose of receiving products or services will be handled in accordance with the Talon Lodge online privacy statement. You are prohibited from posting or transmitting to or from this Site any unlawful, threatening, libelous, defamatory, obscene, pornographic, or other material that would violate any law.</p>
	</div>
	<div class="b-privacy-r">
		<p class="definition no-margin">Chat rooms and other user forums</p>
		<p class="no-margin">Talon Lodge may, but is not obligated to, monitor or review any areas on the Site where users transmit or post Communications or communicate solely with each other, including but not limited to chat rooms, bulletin boards or other user forums, and the content of any such Communications. Talon Lodge, however, will have no liability related to the content of any such Communications, whether or not arising under the laws of copyright, libel, privacy, obscenity, or otherwise. Talon Lodge retains the right to remove messages that include any material Talon Lodge deems abusive, defamatory, obscene or otherwise unacceptable.</p>
		<p class="definition">Links to third-party Websites</p>
		<p class="no-margin">Links on this Site to third-party websites are provided solely as a convenience to you. If you use these links, you will leave this Site. Talon Lodge has not reviewed all of these third-party sites and does not control and is not responsible for any of these sites or their content. Thus, Talon Lodge does not endorse or make any representations about them, or any information, software or other products or materials found there, or any results that may be obtained from using them. If you decide to access any of the third-party websites linked to this Site, you do this entirely at your own risk.</p>
		<p class="definition">Linking to this site</p>
		<p class="no-margin">You may create links to this Site from other sites, but only in accordance with the terms of the Guidelines for linking to Talon Lodge’s Websites and in compliance with all applicable laws.</p>
		<p class="definition">Guidelines for linking to Talon Lodge’s Websites</p>
		<p>A site that links to Talon Lodge’s website:</p>
		<ul class="b-terms-list">
			<li>May link to but not replicate Talon Lodge content</li>
			<li>Should not create a browser or border environment around Talon Lodge content</li>
			<li>Should not imply that Talon Lodge is endorsing it or its products</li>
			<li>Should not misrepresent its relationship with Talon Lodge</li>
			<li>Should not present false information about Talon Lodge products or services</li>
			<li>Should not use the Talon Lodge logo without permission from Talon Lodge</li>
			<li>Should not contain content that could be construed as distasteful, offensive or controversial, and should contain only content that is appropriate for all age groups</li>
		</ul>
		<p class="definition">Procedure for making claims of copyright infringement</p>
		<p class="no-margin">Any notifications of claimed copyright infringement should be mailed to Talon Lodge at 1663 W. Grant Rd, Scottsville, AZ 85745 or sent via e-mail.</p>
		<p class="definition">U.S. government restricted rights</p>
		<p class="no-margin">This Site contains confidential computer software and technical data. A valid License from Talon Lodge is required for possession, use, or copying. Consistent with FAR 12.211 and 12.212, Commercial Computer Software, Computer Software Documentation, and Technical Data for Commercial Items are licensed to the U.S. Government under Talon Lodge’s standard commercial license terms.</p>
		<p>Proprietary Rights</p>
		<p class="no-margin">The software and all pages within our site are the property of Talon Lodge. Any displayed logos, trademarks and/or service marks are also owned by Talon Lodge. All other trademarks, service marks and logos used on our site are the trademarks, service marks or logos of their respective owners.</p>
		<p class="definition">General</p>
		<p class="no-margin">Talon Lodge administers this Site from its offices in Scottsville, Arizona. Talon Lodge makes no representation that materials or services at this Site are appropriate or available for use outside the United States, and access to them from territories where their contents are illegal is prohibited. You may not use or export or re-export the materials or services at this Site or any copy or adaptation in violation of any applicable laws or regulations including without limitation U.S. export laws and regulations. If you choose to access this Site from outside the United States, you do so on your own initiative and are responsible for compliance with applicable local laws. These Terms will be governed by and construed in accordance with the laws of the State of Arizona, without giving effect to any principles of conflicts of laws.</p>
		<p>Talon Lodge may revise these Terms at any time by updating this posting. You should visit this page from time to time to review the then-current Terms because they are binding on you. Certain provisions of these Terms may be superseded by expressly designated legal notices or terms located on particular pages at this Site.</p>
		<p>Revised January 2008</p>
		<p>Note: Anyone linking to Talon Lodge’s website must comply with the Guidelines for Linking to Talon Lodge’s Websites and all applicable laws.</p>
	</div>
</div>